/*
 * generated by Xtext
 */
package jasonide.xtext.asl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class AslRuntimeModule extends jasonide.xtext.asl.AbstractAslRuntimeModule {

}
