/*
* generated by Xtext
*/
package jasonide.xtext.mas2j.ui.contentassist;

import jasonide.xtext.mas2j.ui.contentassist.AbstractMas2jProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class Mas2jProposalProvider extends AbstractMas2jProposalProvider {

}
