/*
* generated by Xtext
*/
package jasonide.xtext.mas2j.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class Mas2jOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
	public Mas2jOutlineTreeProvider() {
		super();
	}
}
